name: 2. Variables
run-name: ${{ github.actor }} is running the ${{ github.workflow }}
on:
  - workflow_dispatch
env:
  FIRSTNAME: "Rodrigo"
  LASTNAME: "Cottin"
  VERSION: ${{ vars.VERSION }}

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      JOBENVVAR: "I am Rodrigo"
    steps:
      - name: Print Repository Variable
        run: |
          echo ${{ vars.VERSION }}
