name: Get Vars Test
run-name: ${{ github.actor }} is running the ${{ github.workflow }}
on:
  workflow_dispatch

jobs:
  get_version:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get current version from environment variable
        run: echo "The value of VERSION is ${{ vars.VERSION }}"
